version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/server"
    schedule: { interval: weekly }
    groups: { security: { patterns: ["*"], update-types: [security] } }
  - package-ecosystem: npm
    directory: "/client"
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }