import type { ContentRecord, EvidenceRef } from "./types.js";
import { createContentRecord } from "./utils.js";

const reviewedAt = "2026-08-16";
const productCommit = "616c05b0e1876a604ce3e798fbd9915c546ba801";

const productArchitecture: EvidenceRef = {
  id: "worker-agent-architecture",
  title: "Worker Agent architecture",
  url: `https://github.com/CodesbyFebin/Worker-Agent/blob/${productCommit}/docs/architecture.md`,
  kind: "product-source",
  publisher: "Worker Agent",
  lastChecked: reviewedAt,
  supports: ["client-server-worker architecture", "tRPC and SSE surfaces", "BullMQ workflow runtime", "MySQL/Drizzle persistence"],
};

const productServer: EvidenceRef = {
  id: "worker-agent-server-runtime",
  title: "Worker Agent API runtime",
  url: `https://github.com/CodesbyFebin/Worker-Agent/blob/${productCommit}/server/_core/index.ts`,
  kind: "implementation-source",
  publisher: "Worker Agent",
  lastChecked: reviewedAt,
  supports: ["Express API", "tRPC middleware", "authenticated organization-scoped SSE", "health and metrics endpoints"],
};

const productSessions: EvidenceRef = {
  id: "worker-agent-session-runtime",
  title: "Worker Agent session implementation",
  url: `https://github.com/CodesbyFebin/Worker-Agent/blob/${productCommit}/server/_core/auth/session.ts`,
  kind: "implementation-source",
  publisher: "Worker Agent",
  lastChecked: reviewedAt,
  supports: ["opaque session token", "HTTP-only cookie", "session revocation", "organization context"],
};

const productDeployment: EvidenceRef = {
  id: "worker-agent-deployment",
  title: "Worker Agent deployment model",
  url: `https://github.com/CodesbyFebin/Worker-Agent/blob/${productCommit}/docs/deployment.md`,
  kind: "product-source",
  publisher: "Worker Agent",
  lastChecked: reviewedAt,
  supports: ["separate API and worker processes", "MySQL/MariaDB", "Redis/BullMQ", "health and readiness checks"],
};

const openAiAgents: EvidenceRef = {
  id: "openai-agents",
  title: "OpenAI developer quickstart — build agents",
  url: "https://platform.openai.com/docs/quickstart/make-your-first-api-request",
  kind: "official-docs",
  publisher: "OpenAI",
  lastChecked: reviewedAt,
  supports: ["agents can take action", "backend orchestration logic", "handoffs between agents"],
};

const mcpSpec: EvidenceRef = {
  id: "mcp-spec",
  title: "Model Context Protocol specification",
  url: "https://modelcontextprotocol.io/specification/2025-11-25",
  kind: "protocol-spec",
  publisher: "Model Context Protocol",
  lastChecked: reviewedAt,
  supports: ["standardized connection between LLM applications, tools, and data sources"],
};

const nistAiRmf: EvidenceRef = {
  id: "nist-ai-rmf",
  title: "NIST AI Risk Management Framework",
  url: "https://www.nist.gov/itl/ai-risk-management-framework",
  kind: "risk-framework",
  publisher: "NIST",
  lastChecked: reviewedAt,
  supports: ["voluntary AI risk management", "trustworthiness considerations across the AI lifecycle"],
};

const nistGenAiProfile: EvidenceRef = {
  id: "nist-genai-profile",
  title: "NIST Generative AI Profile",
  url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence",
  kind: "risk-framework",
  publisher: "NIST",
  lastChecked: reviewedAt,
  supports: ["generative AI risk management", "lifecycle-oriented risk controls"],
};

const owaspAgenticSecurity: EvidenceRef = {
  id: "owasp-agentic-security",
  title: "OWASP Securing Agentic Applications Guide 1.0",
  url: "https://genai.owasp.org/resource/securing-agentic-applications-guide-1-0/",
  kind: "security-guidance",
  publisher: "OWASP GenAI Security Project",
  lastChecked: reviewedAt,
  supports: ["secure design and deployment of agentic applications", "agentic threat mitigation"],
};

const base = {
  publicationStatus: "published" as const,
  reviewStatus: "approved" as const,
  evidenceStatus: "verified" as const,
  rendering: "static-html" as const,
  riskLevel: "standard" as const,
  hasUniqueUserValue: true,
  lastReviewed: reviewedAt,
};

export const contentManifest: ContentRecord[] = [
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent",
    title: "AI Worker Agents: Definition, Architecture, Governance, and Operations",
    description: "A practical guide to AI worker agents: what they are, how they operate, how to deploy them, and where governance and human approval belong.",
    pillarId: "P01",
    clusterId: "P01-HUB",
    parentPillar: "P01",
    contentFile: "content/pages/ai-worker-agent/index.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/",
    relatedPages: ["learn/ai-worker-agent/what-is", "learn/ai-worker-agent/how-it-works", "learn/ai-worker-agent/architecture", "learn/ai-worker-agent/governance"],
    requiredEvidence: ["official-docs", "product-source", "risk-framework"],
    evidence: [openAiAgents, productArchitecture, nistAiRmf],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/what-is",
    title: "What Is an AI Worker Agent?",
    description: "A precise definition of an AI worker agent, the capabilities that make it agentic, and the boundaries that separate it from chatbots and fixed automation.",
    pillarId: "P01",
    clusterId: "C01",
    parentPillar: "P01",
    contentFile: "content/pages/ai-worker-agent/what-is.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/what-is/",
    relatedPages: ["learn/ai-worker-agent", "learn/ai-worker-agent/how-it-works", "learn/ai-worker-agent/architecture"],
    requiredEvidence: ["official-docs", "product-source"],
    evidence: [openAiAgents, productArchitecture],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/how-it-works",
    title: "How AI Worker Agents Work",
    description: "How goals become plans, tool calls, queued work, evidence, events, approvals, and durable results in an AI worker-agent system.",
    pillarId: "P01",
    clusterId: "C02",
    parentPillar: "P01",
    contentFile: "content/pages/ai-worker-agent/how-it-works.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/how-it-works/",
    relatedPages: ["learn/ai-worker-agent/what-is", "learn/ai-worker-agent/architecture", "learn/ai-worker-agent/human-approval"],
    requiredEvidence: ["product-source", "implementation-source", "protocol-spec"],
    evidence: [productArchitecture, productServer, mcpSpec],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/architecture",
    title: "AI Worker Agent Architecture",
    description: "A layered reference architecture for AI worker agents covering the client, API, orchestration, queues, tools, events, persistence, and approval boundaries.",
    pillarId: "P08",
    clusterId: "C03",
    parentPillar: "P08",
    contentFile: "content/pages/ai-worker-agent/architecture.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/architecture/",
    relatedPages: ["learn/ai-worker-agent/how-it-works", "learn/ai-worker-agent/security", "learn/ai-worker-agent/observability"],
    requiredEvidence: ["product-source", "implementation-source", "protocol-spec"],
    evidence: [productArchitecture, productServer, mcpSpec],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/implementation",
    title: "AI Worker Agent Implementation Roadmap",
    description: "A staged implementation roadmap for moving from one bounded worker-agent use case to a governed production runtime with observability and human approval.",
    pillarId: "P02",
    clusterId: "C01",
    parentPillar: "P02",
    contentFile: "content/pages/ai-worker-agent/implementation.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/implementation/",
    relatedPages: ["learn/ai-worker-agent/architecture", "learn/ai-worker-agent/security", "learn/ai-worker-agent/self-hosting"],
    requiredEvidence: ["product-source", "risk-framework"],
    evidence: [productDeployment, productArchitecture, nistAiRmf],
  }),
  createContentRecord({
    ...base,
    riskLevel: "high" as const,
    slug: "learn/ai-worker-agent/security",
    title: "AI Worker Agent Security",
    description: "Security controls for agentic systems: identity, least privilege, tool boundaries, session protection, data isolation, prompt/tool risks, logging, and recovery.",
    pillarId: "P10",
    clusterId: "C04",
    parentPillar: "P10",
    contentFile: "content/pages/ai-worker-agent/security.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/security/",
    relatedPages: ["learn/ai-worker-agent/architecture", "learn/ai-worker-agent/governance", "learn/ai-worker-agent/human-approval"],
    requiredEvidence: ["security-guidance", "risk-framework", "implementation-source"],
    evidence: [owaspAgenticSecurity, nistGenAiProfile, productServer, productSessions],
  }),
  createContentRecord({
    ...base,
    riskLevel: "high" as const,
    slug: "learn/ai-worker-agent/governance",
    title: "AI Worker Agent Governance",
    description: "How to govern AI worker agents with explicit authority boundaries, evidence, approvals, auditability, monitoring, and lifecycle risk management.",
    pillarId: "P10",
    clusterId: "C05",
    parentPillar: "P10",
    contentFile: "content/pages/ai-worker-agent/governance.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/governance/",
    relatedPages: ["learn/ai-worker-agent/security", "learn/ai-worker-agent/human-approval", "learn/ai-worker-agent/observability"],
    requiredEvidence: ["risk-framework", "security-guidance", "product-source"],
    evidence: [nistAiRmf, nistGenAiProfile, owaspAgenticSecurity, productArchitecture],
  }),
  createContentRecord({
    ...base,
    riskLevel: "high" as const,
    slug: "learn/ai-worker-agent/human-approval",
    title: "Human Approval in AI Worker Agent Systems",
    description: "Where human approval belongs in agentic workflows, which actions should pause for review, and how to preserve accountability without removing automation benefits.",
    pillarId: "P10",
    clusterId: "C08",
    parentPillar: "P10",
    contentFile: "content/pages/ai-worker-agent/human-approval.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/human-approval/",
    relatedPages: ["learn/ai-worker-agent/governance", "learn/ai-worker-agent/security", "learn/ai-worker-agent/how-it-works"],
    requiredEvidence: ["risk-framework", "security-guidance", "product-source"],
    evidence: [nistAiRmf, owaspAgenticSecurity, productArchitecture],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/observability",
    title: "AI Worker Agent Observability",
    description: "What to observe in an AI worker-agent runtime: health, readiness, queue state, workflow events, model/tool decisions, errors, costs, and evidence trails.",
    pillarId: "P30",
    clusterId: "C07",
    parentPillar: "P30",
    contentFile: "content/pages/ai-worker-agent/observability.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/observability/",
    relatedPages: ["learn/ai-worker-agent/architecture", "learn/ai-worker-agent/security", "learn/ai-worker-agent/self-hosting"],
    requiredEvidence: ["product-source", "implementation-source"],
    evidence: [productDeployment, productServer, productArchitecture],
  }),
  createContentRecord({
    ...base,
    slug: "learn/ai-worker-agent/self-hosting",
    title: "Self-Hosting an AI Worker Agent Runtime",
    description: "A deployment model for self-hosting an AI worker-agent stack with separate web, API, worker, database, queue, health, and readiness boundaries.",
    pillarId: "P08",
    clusterId: "C07",
    parentPillar: "P08",
    contentFile: "content/pages/ai-worker-agent/self-hosting.md",
    canonicalUrl: "https://workeragent.cloud/learn/ai-worker-agent/self-hosting/",
    relatedPages: ["learn/ai-worker-agent/implementation", "learn/ai-worker-agent/architecture", "learn/ai-worker-agent/observability"],
    requiredEvidence: ["product-source", "implementation-source"],
    evidence: [productDeployment, productServer],
  }),
];
